package com.wilson688.algorithms.projecteuler;
//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Problem2 {

    public static final int MAX_VALUE = 4000000;
    static int sum = 0;
    static int[] nums = new int[MAX_VALUE];
    public int solve() {

        int i = 2;

        while (sum < MAX_VALUE) {
            nums[i] = nums[i - 1] + nums[i-2];

            if (nums[i] % 2 == 0) sum += nums[i];
            i++;

        }

        return sum;
    }

    public static void main(String[] args) {
        nums[0] = 1;
        nums[1] = 1;

        Problem2 prb = new Problem2();
        long start = System.currentTimeMillis();
        System.out.println(prb.solve());
        System.out.println(System.currentTimeMillis() - start);
    }
}
